# -*- coding: utf-8 -*-
"""AUTOMATION OF INVOICE UI_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNJU1Lb3fqLcjkl9lzbipFc-E0gYJjJn
"""

#  AUTOMATION OF INVOICE (OCR IMAGE + VOICE INPUT)
!pip install pytesseract SpeechRecognition Pillow ipywidgets
import pytesseract
from PIL import Image
import speech_recognition as sr
import io
import ipywidgets as widgets
from IPython.display import display, clear_output

# ===Input feilds===
product = widgets.Text(description = "Poduct Name:VC pillow,pillow cover vc 85,pillow cover 100,lunch towel vc25,lunch towel20,lunch towel32,ceramic bowl,chn avon bowel,ruby food cover,ms straw tumbler,pigeon fork tea,dk mosquito bat, buds tulips paper,absara eraser,idly cloth")
quantity = widgets.Text(description = "Quantity:1,1,1,1,1,1,1,1,1,1,1,1,3,1,2")
rate = widgets.Text(description = "Rate:250,85,100,25,20,32,150,25,130,210,142,280,28,5,35")
add_button = widgets.Button(description = "Add Item:")
sub_total = widgets.Button(description = "Sub Total:")
sgst = widgets.Button(description = "SGST:")
cgst = widgets.Button(description ="CGST:")
igst = widgets.Button(description = "IGST:")
Grand_total = widgets.Button(description = "Grand Total:")

# ===OCR Upload Widgets===
upload_button = widgets.FileUpload(description = "Upload Image:/content/IMG_20250810_114713729_OCR.pdf,/content/IMG_20250810_114736044_OCR.pdf,/content/IMG_20250810_114633860_OCR.pdf")
ocr_output = widgets.Output()

# ===Voice Buttons===
voice_button = widgets.Button(description = "Voice Input:")
voice_product = widgets.Button(description = "Speak Product:")
voice_quantity = widgets.Button(description = "Speak Quantity:")
voice_rate = widgets.Button(description = "Speak Rate:")
voice_output = widgets.Output()

# ===Invoice display ===
invoice_items = widgets.Output()

# ===Recognize Speech===
def Recognize_speech():
  recognizer = sr.Recognizer()
  with sr.Microphone() as source:
    with voice_output:
      clear_output()
      print("Listening...")
      audio = recognizer.listen(source)
    try:
      text = recognizer.recognize_google(audio)
      with voice_output:
        clear_output()
        print("Recognized:",text)
        return text
    except sr.UnknownValueError:
      with voice_output:
        clear_output()
        print("Could not understand audio")
        return None
    except sr.RequestError:
      with voice_output:
        print("Could not request results from Google Speech Recognition service")
        return None

# Add item function
def add_item(b):
  with invoice_items:
    clear_output()
    print(f"Product:{product.value}")
    print(f"Quantity:{quantity.value}")
    print(f"Rate:{rate.value}")
    print(f"Total:{float(quantity.value)*float(rate.value)}")
    print("-------------------------")
    product.value = ""
    quantity.value = ""
    rate.value = ""
    show_invoice()

    display(upload_button,ocr_output,product,quantity,rate,add_button)
    display(invoice_items)
    display(voice_button,voice_product,voice_quantity,voice_rate,voice_output)

# ===voice Handlers===
def on_voice_product(b):
  text = Recognize_speech()
  if text:
    product.value = text

def on_voice_quantity(b):
  text = Recognize_speech()
  if text and text.isdigit():
    quantity.value = int(text)

def on_voice_rate(b):
  text = Recognize_speech()
  if text and text.replace(',', '').isdigit():
    rate.value = float(text.replace(',', ''))


voice_product.on_click(on_voice_product)
voice_quantity.on_click(on_voice_quantity)
voice_rate.on_click(on_voice_rate)
add_button.on_click(add_item)

# TITLE
title = widgets.HTML(value = "<h2>VOICE INPUTS</h2>")

# Display voice inputs
display(title,voice_button,voice_product, voice_quantity, voice_rate, voice_output,add_button,sub_total,sgst,cgst,igst,Grand_total)

#===OCR Handler===
def process_image(change):
  with ocr_output:
    clear_output()
    try:
      uploaded_file = upload_button.value
      if not uploaded_file:
        print("No file uploaded")
        return
      file = uploaded_file[0]
      image_data = file['content']
      image = Image.open(io.BytesIO(image_data))
      image_text = pytesseract.image_to_string(image)
      print("Extracted Text:")
      print(image_text)

      # Sample extract attempt(first line with numbers at end)
      lines = image_text.split('\n')
      for line in lines:
        parts = line.split()
        if len(parts)>=3 and parts[-2].isdigit():
          try:
            product.value = parts[0]
            quantity.value = int(parts[-2])
            rate.value = float(parts[-1])
            break
          except IndexError:
            continue
          except ValueError:
            continue
    except Exception as e:
      print(f"An error occurred: {e}")

upload_button.observe(process_image, names='value')


# TITLE
title = widgets.HTML(value = "<h2>OCR IMAGE INPUTS</h2>")

display(title,upload_button, product, quantity, rate, add_button,sub_total,sgst,cgst,igst,Grand_total)

# ===Display Invoice===
invoice_item = []
def show_invoice():
  with invoice_items:
    clear_output()
    total_amount = 0
    print("Invoice")
    print("--------------------------")
    for item in invoice_item:
      print(f"Product:{item['product']}")
      print(f"Quantity:{item['quantity']}")
      print(f"Rate:{item['rate']}")
      print(f"Sub total:{item['sub total']}")
      print(f"Sgst:{item['sgst']}")
      print(f"Cgst:{item['cgst']}")
      print(f"Igst:{item['igst']}")
      print(f"Grand Total:{item['grand total']}")
      Grand_total_amount += item['grand total']
    print(f"Grand Total Amount: {'grand_total_amount'}")
show_invoice()

# Display UI
print("Upload Invoice Image or mic Use voice to fill invoice Feilds")