# -*- coding: utf-8 -*-
"""FRAUD  DETECTION UI_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPKIyR2P3XBQbZntKW1o9IT7npzESCWx
"""

# FRAUD DETECTION UI_AI
import io
import pandas as pd
import numpy as np
from IPython.display import display, clear_output
import ipywidgets as widgets
import matplotlib.pyplot as plt
from datetime import datetime
import os
import uuid

# Try to import IsolationForest:if missing handle gracefully
try:
  from sklearn.ensemble import IsolationForest
  SKLEARN_INSTALLED = True
except Exception:
  SKLEARN_INSTALLED = False
  print("sklearn not installed")

# WIDGETS

upload = widgets.FileUpload(accept=".csv,.xlsx", multiple=False, description="Upload Transaction")
algo_dropdown = widgets.Dropdown(options=[("Rule-based(amount threshold)", "rule"), ("Z-score(statistical outliers)", "zscore"), ("IsolationForest(ML)", "iforest" if SKLEARN_INSTALLED else "iforest_disabled")], value="rule", description="Algorithm:")
if not SKLEARN_INSTALLED:
  algo_dropdown.options = [("Rule based(amount threshold)", "rule"), ("Z-score(statistical outliers)", "zscore"), ("isolationForest(sckit-learn not found)", "iforest_disabled")]

amount_threshold = widgets.FloatText(value=10000.00, description="Amount threshold:")
zscore_threshold = widgets.FloatSlider(value=3.00, min=1.00, max=6.00, step=0.1, description="Z-Threshold:")
iforest_contamination = widgets.FloatSlider(value=0.01, min=0.00, max=0.3, step=0.005, description="Iforest contamination:")
date_col = widgets.Text(value="Date", description="Date column:")
amount_col = widgets.Text(value="Amount", description="Amount column:")
desc_col = widgets.Text(value="Description", description="Description column:")

run_button = widgets.Button(description="Run Detection", button_style="primary")
export_button = widgets.Button(description="Export Results", button_style="primary")
output = widgets.Output(layout={"border": "1px solid black"})

def add_rules(b):
  with output:
    clear_output()
    print("Add Rules button clicked. Implement rule adding logic here.")

add_button = widgets.Button(description = "Add Rules",button_style = "primary")
add_button.on_click(add_rules)

def detect_iforest(df, amount_col, contamination):
  if not SKLEARN_INSTALLED:
    print("Isolation Forest requires sklearn which is not installed.")
    return pd.DataFrame() # Return empty DataFrame if sklearn is not available
  df = df.copy()
  model = IsolationForest(contamination=contamination, random_state=42)
  df['fraud_score'] = model.fit_predict(df[[amount_col]])
  # IsolationForest returns -1 for outliers and 1 for inliers
  return df[df['fraud_score'] == -1]

def detect_zscore(df, amount_col, threshold):
  df = df.copy()
  mean_amount = df[amount_col].mean()
  std_amount = df[amount_col].std()
  df['z_score'] = (df[amount_col] - mean_amount) / std_amount
  df['fraud_score'] = (np.abs(df['z_score']) > threshold).astype(int)
  return df[np.abs(df['z_score']) > threshold]

# Global state
transaction_df = None
flagged_df = None
last_export_path = None

def load_file_from_upload(upload_dict):
  if len(upload_dict.values()) == 0:
    return None
  file_info = list(upload_dict.values())[0]
  content = file_info['content']
  file_name = file_info['name']
  try:
    if file_name.lower().endswith(".csv"):
      return pd.read_csv(io.BytesIO(content))
    elif file_name.lower().endswith((".xls",".xlsx")):
      return pd.read_excel(io.BytesIO(content))
    else:
      return None
  except Exception as e:
    print(f"Error loading file:{e}")
    return None

def prepare_df(df,date_col,amount_col,desc_col):
  try:
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')
  except Exception as e:
    print(f"Error converting date column: {e}")

  try:
    df[amount_col] = df[amount_col].astype(float)
  except Exception as e:
    print(f"Error converting amount column: {e}")

  try:
    df[desc_col] = df[desc_col].astype(str)
  except Exception as e:
    print(f"Error converting description column: {e}")

  df.dropna(subset=[amount_col], inplace=True)
  return df





def detect_rule_based(df, amount_col, amount_threshold):
  df =df.copy()
  df['fraud_score'] = (df[amount_col]>=amount_threshold).astype(int)
  return df[df[amount_col]>=amount_threshold]

# Display UI
display(upload,algo_dropdown,amount_threshold,zscore_threshold,iforest_contamination,date_col,amount_col,desc_col,run_button,export_button,add_button,output)