# -*- coding: utf-8 -*-
"""INVENTORY MANAGEMENT UI_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Id5pD1QvwFjXxP8cgstwJkHO4yBGYaBu
"""

# INVENTORY MANAGEMENT UI_AI
import ipywidgets as widgets
from IPython.display import display,clear_output
import pandas as pd

# Initialize inventory as an empty DataFrame
inventory = pd.DataFrame(columns=['Item','Quantity','Price','Amount'])

# widgets
item_input = widgets.Text(description='Item:linedates syrup 500gm,vim dishwash 750ml,orieo biscuts,kinder joy,diary milk chocklet')
quantity_input = widgets.IntText(description='Quantity:1,1,2,1,4')
price_input = widgets.FloatText(description='Price:200,185,28,45,19')
amount_input = widgets.FloatText(description = 'Amount:200,185,56,45,76')
sub_total_value = widgets.FloatText(description = 'Sub_Total:')
cgst_input = widgets.FloatText(description='CGST:9/100')
sgst_input = widgets.FloatText(description='SGST:9/100')
Grand_Total = widgets.FloatText(description='Grand_Total:')
add_button = widgets.Button(description = "Add/Update Item:")
button_style = "success"
delete_item_input = widgets.Text(description='Delete Item:')
delete_Button = widgets.Button(description = "Delete Item:")
button_style = "danger"
output = widgets.Output()

# Display inventory table
def display_inventory():
  with output:
    clear_output()
    if inventory.empty:
      print('Inventory is empty')
    else:
        display(inventory)

# Add inventory item
def add_to_inventory(b):
  global inventory
  item = item_input.value
  quantity = quantity_input.value
  price = price_input.value
  amount_input.value = quantity * price
  if item:
    if item in inventory["Item"].values:
        inventory.loc[inventory['Item'] == item, 'Quantity'] += quantity
    else:
        new_item = pd.DataFrame([[item, quantity, price, amount_input.value]], columns=inventory.columns)
        inventory = pd.concat([inventory, new_item], ignore_index=True)
    display_inventory()

# Delete  an item from inventory
def delete_from_inventory(b):
  global inventory
  item_to_delete = delete_item_input.value.strip()
  if item_to_delete:
    inventory = inventory[inventory['Item'] != item_to_delete]
    display_inventory()

# calculation of inventory
def calculate_inventory_value():
  # Calculate the subtotal for each item
  inventory['Sub_Total_value'] = inventory['Quantity'] * inventory['Price']==['Amount']

  # Calculate CGST and SGST (assuming a 9% rate for both)
  CGST = inventory['Sub_Total_value'] * 0.09
  SGST = inventory['Sub_Total_value'] * 0.09

  # Calculate the Grand Total for each item
  inventory['Grand_Total'] = inventory['Sub_Total_value'] + CGST + SGST

  # Return the sum of the Grand Total for all items
  return inventory['Grand_Total'].sum()

# Calculate Sub total value
def calculate_sub_total_value(price,quantity):
  return (price*quantity)

# Calculate SGST and CGST (Assuming 9% rate for both)
def calculate_sgst(price,quantity):
  return (price*quantity)*0.09

def calculate_cgst(price,quantity):
  return (price*quantity)* 0.09

# Calculate Grand Total value

def calculate_grand_total_value(price,quantity):
  sub_total_value = calculate_sub_total_value(price,quantity)
  sgst = calculate_sgst(price,quantity)
  cgst = calculate_cgst(price,quantity)
  grand_total_value = sub_total_value + sgst + cgst
  return grand_total_value.sum()

# TITLE
title = widgets.HTML(value="<h2>INVENTORY input</h2>")

# Bind button actions
add_button.on_click(add_to_inventory)
delete_Button.on_click(delete_from_inventory)

# Layout
ui = widgets.VBox([
    widgets.HBox([title, item_input, quantity_input, price_input, amount_input, sub_total_value, sgst_input, cgst_input, Grand_Total]),
    widgets.HBox([add_button, delete_item_input, delete_Button,]),
    output
])

display(ui)

