# -*- coding: utf-8 -*-
"""OFFICE BOOKKEEPING UI_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXCwR-y2DraY1UuL9BAPDbZNGze4luo8
"""

# OFFICE BOOKKEEPING UI_AI
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd

# Store bookkeeping entries
bookkeeping_data = []

# Widgets
date_input = widgets.DatePicker(description='Date:01-07-2025,02-07-2025,03-07-2025,04-07-2025,05-07-2025,07-07-2025,08-07-2025,09-07-2025')
description_input = widgets.Text(description ='Description:uber ride to meeting,office chair purchase,Monthly Internet bill,Flight to conference,Printer ink order,Team Lunch,Hotel stay for seminar,Sale of Goods')
type_input = widgets.Dropdown(options=['Income','Expenses'],description='Type:Expenses,Expenses,Expenses,Expenses,Expenses,Expenses,Expense,Income')
amount_input = widgets.FloatText(description='Amount:1500,12000,6000,30000,4500,8000,50000,150000')
add_button = widgets.Button(description='Add Entry',button_style='success')

# Output area
output = widgets.Output()

# Functions to add entry
def add_entry(b):
  entry={
      'Date':date_input.value,
      'Description':description_input.value,
      'Type':type_input.value,
      'Amount':amount_input.value}
  bookkeeping_data.append(entry)
  update_output()

# Functions to display table
def update_output():
  with output:
    output.clear_output()
    df = pd.DataFrame(bookkeeping_data)
    if not df.empty:
      display(df)
    else:
      print('No entries yet')

# Link button to function
add_button.on_click(add_entry)

# Display UI elements
output = widgets.Output()
UI = widgets.VBox([date_input,description_input,type_input,amount_input,add_button, output])
display(UI)

# Functions to display table
def update_output():
  with output:
    output.clear_output()
    df = pd.DataFrame(bookkeeping_data)
    if not df.empty:
      display(df)
      total_income = df[df['Type'] == 'Income']['Amount'].sum()
      total_expenses = df[df['Type'] == 'Expenses']['Amount'].sum()

    else:
      print('No entries yet')
      sub_total_income.value = 'Sub total income: 0'
      sub_total_expenses.value = 'Sub total expenses: 0'