# -*- coding: utf-8 -*-
"""PROFIT AND LOSS STATEMENT UI_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pc0TDzTc3krMXbfUknlt6QMx6jvxcawC
"""

# PROFIT AND LOSS STATEMENT UI_AI
import ipywidgets as widgets
from IPython.display import display, clear_output

# Revenue inputs
sales = widgets.FloatText(description='Sales:150000')
service_income=widgets.FloatText(description='Service_Income:30000')
interest_income=widgets.FloatText(description='Interest_income:5000')
other_income=widgets.FloatText(description='Other_income:0')
total_income=widgets.FloatText(description='Total_income:185000')

# Expense inputs
salaries=widgets.FloatText(description='Salaries:25000')
rent=widgets.FloatText(description='Rent:10000')
utilities=widgets.FloatText(description='Utilities:3000')
other_expenses=widgets.FloatText(description='Other_expenses:0')
total_expenses=widgets.FloatText(description='Total_expenses:38000')

# Button to calculate
calculate_button=widgets.Button(description='Calculate P&L',button_style='success')

# Output area
output=widgets.Output()

# Calculation Function
def calculate_pnl(b):
  with output:
    output.clear_output()
    # Totals
    total_revenue=sales.value+service_income.value+interest_income.value+other_income.value
    total_expenses=salaries.value+rent.value+utilities.value+other_expenses.value
    net_profit=total_revenue-total_expenses

    # Display results
    print("Profit and Loss Statement")
    print(f"Total Revenue:${total_revenue:,.2f}")
    print(f"Total Expenses:${total_expenses:,.2f}")
    print(f"Net Profit/Loss:${net_profit:,.2f} {'(Profit)' if net_profit >= 0 else '(Loss)'}")

# Totals
# total_revenue=sales.value+service_income.value+interest_income.value+other_income.value
# total_expenses=salaries.value+rent.value+utilities.value+other_expenses.value
# net_profit=total_revenue-total_expenses

# Display results
# print("Profit and Loss Statement")
#print(f"Total Revenue:${total_revenue:,.2f}")
#print(f"Total Expenses:${total_expenses:,.2f}")
#print(f"Net Profit/Loss:${net_profit:,.2f} {'(Profit)' if net_profit >= 0, else:'(Loss)'}")

# Bind button
calculate_button.on_click(calculate_pnl)

# Layout
display(widgets.HTML("<h3>Enter Profit and Loss Details</h3>"))
display(widgets.VBox([widgets.HTML("<b> Revenue</b>"),sales,service_income,interest_income,widgets.HTML("<b>Expenses</b>"),salaries,rent,utilities,other_expenses,
                    calculate_button,output]))