# -*- coding: utf-8 -*-
"""TAX-GST  UI_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNDNmWpXHL3pp57Aj-bFYFepBWlwHNtT
"""

# TAX: GST
import ipywidgets as widgets
from IPython.display import display,clear_output

# Input Widgets
amount = widgets.FloatText(description = "Amount:",value=1000000.00)
cgst = widgets.FloatText(description = "CGST:",value=9.00)
sgst = widgets.FloatText(description ="SGST:",value=9.00)
igst = widgets.FloatText(description ="IGST:",value=0.00)

# Labels for outputs
total_tax_label = widgets.Label(value = "Total Tax:0.0")
grand_total_label = widgets.Label(value = "Grand Total:0.0")

# Button
calculate_button = widgets.Button(description = "Calculate",button_style = 'primary')

# Output display
output = widgets.Output()

# Calculation function
def calculate_tax(b):
  with output:
    clear_output()
    amount_value = amount.value
    cgst_value = amount_value * (cgst.value / 100)
    sgst_value = amount_value * (sgst.value / 100)
    igst_value = amount_value * (igst.value / 100)
    total_tax  = cgst_value + sgst_value + igst_value
    grand_total = amount_value + total_tax

    total_tax_label.value = f"Total Tax:{total_tax:.2f}"
    grand_total_label.value =f"Grand Total:{grand_total:.2f}"
    print(f"Amount:{amount_value}")
    print(f"CGST:{cgst_value:.2f}")
    print(f"SGST:{sgst_value:.2f}")
    print(f"IGST:{igst_value:.2f}")
    print(f"Total Tax:{total_tax:.2f}")
    print(f"Grand Total:{grand_total:.2f}")

# Bind button click
calculate_button.on_click(calculate_tax)

# Display UI
ui = widgets.VBox([amount,cgst,sgst,igst,total_tax_label,grand_total_label,calculate_button,output])
display(ui)