import { useState, useEffect } from "react";
import { VoiceButton } from "@/components/ui/VoiceButton";
import { Button } from "@/components/ui/button";
import { API_ENDPOINTS } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Calculator, Download, TrendingUp, AlertCircle, CheckCircle, Building, Scale } from "lucide-react";
import { useNavigate } from "react-router-dom";

const BalanceSheet = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    currentAssets: "",
    nonCurrentAssets: "",
    currentLiabilities: "",
    nonCurrentLiabilities: "",
    equity: "",
  });
  const [balanceSheet, setBalanceSheet] = useState(null);


  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const generateBalanceSheet = async () => {
    const currentAssets = parseFloat(formData.currentAssets) || 0;
    const nonCurrentAssets = parseFloat(formData.nonCurrentAssets) || 0;
    const currentLiabilities = parseFloat(formData.currentLiabilities) || 0;
    const nonCurrentLiabilities = parseFloat(formData.nonCurrentLiabilities) || 0;
    const equity = parseFloat(formData.equity) || 0;

    // Calculate totals like Python file
    const totalAssets = currentAssets + nonCurrentAssets;
    const totalLiabilities = currentLiabilities + nonCurrentLiabilities;
    const totalLiabilitiesEquity = totalLiabilities + equity;

    const balanced = Math.abs(totalAssets - totalLiabilitiesEquity) < 0.01;

    const dataToSave = {
      currentAssets,
      nonCurrentAssets,
      totalAssets,
      currentLiabilities,
      nonCurrentLiabilities,
      totalLiabilities,
      equity,
      totalLiabilitiesEquity,
      balanced,
    };

    setBalanceSheet(dataToSave);

    try {
      const res = await fetch(`${API_ENDPOINTS.BALANCE}/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(dataToSave),
      });
      const result = await res.json();
      if (!res.ok) console.error("Error saving data:", result);
    } catch (error) {
      console.error("Error connecting to backend:", error);
    }
  };

  const downloadReport = () => {
    if (!balanceSheet) return;

    const content = `
╔═══════════════════════════════════════════════╗
║       BALANCE SHEET - ${new Date().toLocaleDateString()}           ║
╚═══════════════════════════════════════════════╝

ASSETS
────────────────────────────────────────────────
Current Assets:             ₹${balanceSheet.currentAssets.toFixed(2)}
Non-Current Assets:         ₹${balanceSheet.nonCurrentAssets.toFixed(2)}
────────────────────────────────────────────────
Total Assets:               ₹${balanceSheet.totalAssets.toFixed(2)}

LIABILITIES
────────────────────────────────────────────────
Current Liabilities:        ₹${balanceSheet.currentLiabilities.toFixed(2)}
Non-Current Liabilities:    ₹${balanceSheet.nonCurrentLiabilities.toFixed(2)}
────────────────────────────────────────────────
Total Liabilities:          ₹${balanceSheet.totalLiabilities.toFixed(2)}

EQUITY
────────────────────────────────────────────────
Equity:                     ₹${balanceSheet.equity.toFixed(2)}

════════════════════════════════════════════════
Total Liabilities + Equity: ₹${balanceSheet.totalLiabilitiesEquity.toFixed(2)}
════════════════════════════════════════════════

STATUS: ${balanceSheet.balanced ? '✓ BALANCED' : '✗ UNBALANCED'}

${balanceSheet.balanced ? 'Balance sheet is balanced' : 'Balance sheet is NOT balanced'}

Generated by SHREE ANDAL AI SOFTWARE SOLUTIONS (OPC) PRIVATE LIMITED
Powered by Advanced Financial Analytics Engine ✨
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Balance_Sheet_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const handleBackToDashboard = () => {
    navigate("/dashboard");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-950 relative overflow-hidden">
      {/* Animated Background Effects */}
      <div className="absolute inset-0 bg-[linear-gradient(rgba(59,130,246,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(59,130,246,0.03)_1px,transparent_1px)] bg-[size:50px_50px]" />

      {/* Static gradient circles instead of mouse-following orb */}
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-indigo-600/10 rounded-full blur-[120px] pointer-events-none" />

      {/* Floating particles */}
      <div className="absolute top-20 left-20 w-2 h-2 bg-blue-400 rounded-full animate-ping" />
      <div className="absolute top-40 right-40 w-3 h-3 bg-cyan-400 rounded-full animate-pulse" />
      <div className="absolute bottom-32 left-1/3 w-2 h-2 bg-indigo-400 rounded-full animate-ping" style={{ animationDelay: '1s' }} />

      {/* Header */}
      <header className="relative backdrop-blur-xl bg-white/5 border-b border-blue-400/20 shadow-2xl shadow-blue-500/20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Button
            variant="ghost"
            onClick={handleBackToDashboard}
            className="mb-4 text-blue-200 hover:text-blue-100 hover:bg-white/10 transition-all duration-300 group backdrop-blur-xl"
          >
            <ArrowLeft className="mr-2 h-4 w-4 group-hover:-translate-x-1 transition-transform" />
            Back to Dashboard
          </Button>
          <div className="flex items-center gap-4">
            <div
              className="p-4 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-2xl backdrop-blur-xl border border-blue-400/30 shadow-2xl shadow-blue-500/40"
            >
              <Scale className="h-8 w-8 text-blue-300" />
            </div>
            <div>
              <h1 className="text-4xl font-black bg-gradient-to-r from-blue-400 via-cyan-400 to-indigo-400 bg-clip-text text-transparent drop-shadow-[0_0_30px_rgba(59,130,246,0.8)]">
                Balance Sheet Generator
              </h1>
              <p className="text-blue-200/80 font-medium mt-1">Create comprehensive financial statements with real-time validation</p>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Input Card */}
          <Card
            className="backdrop-blur-2xl bg-white/10 border border-blue-400/30 shadow-2xl shadow-blue-500/40 rounded-3xl overflow-hidden group hover:-translate-y-2 transition-all duration-500"
          >
            <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 via-transparent to-cyan-500/10 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

            <CardHeader className="relative">
              <div className="absolute top-4 right-4 flex gap-2">
                <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
                <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse" style={{ animationDelay: '0.5s' }} />
              </div>
              <CardTitle className="text-2xl font-bold text-white">Enter Balance Sheet Data</CardTitle>
              <CardDescription className="text-blue-300">Input your financial values below</CardDescription>
            </CardHeader>

            <CardContent className="space-y-6 relative">
              {/* Assets Section */}
              <div className="space-y-4 p-6 rounded-2xl bg-gradient-to-br from-blue-500/5 to-cyan-500/5 border border-blue-400/20 backdrop-blur-xl">
                <h3 className="font-bold text-lg text-white flex items-center gap-2">
                  <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center shadow-lg shadow-blue-500/50">
                    <Building className="h-4 w-4 text-white" />
                  </div>
                  Assets
                </h3>
                <div className="space-y-2">
                  <Label htmlFor="currentAssets" className="text-white font-medium">Current Assets (₹)</Label>
                  <div className="flex items-center gap-2">
                    <Input
                      id="currentAssets"
                      type="number"
                      placeholder="e.g., 150000.00"
                      value={formData.currentAssets}
                      onChange={(e) => handleInputChange("currentAssets", e.target.value)}
                      className="bg-slate-900/50 text-white border-blue-400/30 backdrop-blur-xl focus:border-blue-400 focus:ring-2 focus:ring-blue-400/50 transition-all placeholder:text-blue-400/30"
                    />
                    <VoiceButton
                      onTranscript={(text) => handleInputChange("currentAssets", text)}
                      onClear={() => handleInputChange("currentAssets", "")}
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="nonCurrentAssets" className="text-white font-medium">Non-Current Assets (₹)</Label>
                  <div className="flex items-center gap-2">
                    <Input
                      id="nonCurrentAssets"
                      type="number"
                      placeholder="e.g., 450000.00"
                      value={formData.nonCurrentAssets}
                      onChange={(e) => handleInputChange("nonCurrentAssets", e.target.value)}
                      className="bg-slate-900/50 text-white border-blue-400/30 backdrop-blur-xl focus:border-blue-400 focus:ring-2 focus:ring-blue-400/50 transition-all placeholder:text-blue-400/30"
                    />
                    <VoiceButton
                      onTranscript={(text) => handleInputChange("nonCurrentAssets", text)}
                      onClear={() => handleInputChange("nonCurrentAssets", "")}
                    />
                  </div>
                </div>
              </div>

              {/* Liabilities Section */}
              <div className="space-y-4 p-6 rounded-2xl bg-gradient-to-br from-orange-500/5 to-red-500/5 border border-orange-400/20 backdrop-blur-xl">
                <h3 className="font-bold text-lg text-white flex items-center gap-2">
                  <div className="w-8 h-8 bg-gradient-to-br from-orange-500 to-red-500 rounded-lg flex items-center justify-center shadow-lg shadow-orange-500/50">
                    <TrendingUp className="h-4 w-4 text-white" />
                  </div>
                  Liabilities
                </h3>
                <div className="space-y-2">
                  <Label htmlFor="currentLiabilities" className="text-white font-medium">Current Liabilities (₹)</Label>
                  <div className="flex items-center gap-2">
                    <Input
                      id="currentLiabilities"
                      type="number"
                      placeholder="e.g., 60000.00"
                      value={formData.currentLiabilities}
                      onChange={(e) => handleInputChange("currentLiabilities", e.target.value)}
                      className="bg-slate-900/50 text-white border-blue-400/30 backdrop-blur-xl focus:border-blue-400 focus:ring-2 focus:ring-blue-400/50 transition-all placeholder:text-blue-400/30"
                    />
                    <VoiceButton
                      onTranscript={(text) => handleInputChange("currentLiabilities", text)}
                      onClear={() => handleInputChange("currentLiabilities", "")}
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="nonCurrentLiabilities" className="text-white font-medium">Non-Current Liabilities (₹)</Label>
                  <div className="flex items-center gap-2">
                    <Input
                      id="nonCurrentLiabilities"
                      type="number"
                      placeholder="e.g., 140000.00"
                      value={formData.nonCurrentLiabilities}
                      onChange={(e) => handleInputChange("nonCurrentLiabilities", e.target.value)}
                      className="bg-slate-900/50 text-white border-blue-400/30 backdrop-blur-xl focus:border-blue-400 focus:ring-2 focus:ring-blue-400/50 transition-all placeholder:text-blue-400/30"
                    />
                    <VoiceButton
                      onTranscript={(text) => handleInputChange("nonCurrentLiabilities", text)}
                      onClear={() => handleInputChange("nonCurrentLiabilities", "")}
                    />
                  </div>
                </div>
              </div>

              {/* Equity Section */}
              <div className="space-y-4 p-6 rounded-2xl bg-gradient-to-br from-green-500/5 to-emerald-500/5 border border-green-400/20 backdrop-blur-xl">
                <h3 className="font-bold text-lg text-white flex items-center gap-2">
                  <div className="w-8 h-8 bg-gradient-to-br from-green-500 to-emerald-500 rounded-lg flex items-center justify-center shadow-lg shadow-green-500/50">
                    <Calculator className="h-4 w-4 text-white" />
                  </div>
                  Equity
                </h3>
                <div className="space-y-2">
                  <Label htmlFor="equity" className="text-white font-medium">Equity (₹)</Label>
                  <div className="flex items-center gap-2">
                    <Input
                      id="equity"
                      type="number"
                      placeholder="e.g., 400000.00"
                      value={formData.equity}
                      onChange={(e) => handleInputChange("equity", e.target.value)}
                      className="bg-slate-900/50 text-white border-blue-400/30 backdrop-blur-xl focus:border-blue-400 focus:ring-2 focus:ring-blue-400/50 transition-all placeholder:text-blue-400/30"
                    />
                    <VoiceButton
                      onTranscript={(text) => handleInputChange("equity", text)}
                      onClear={() => handleInputChange("equity", "")}
                    />
                  </div>
                </div>
              </div>

              <Button
                onClick={generateBalanceSheet}
                className="w-full bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white font-bold py-6 rounded-xl shadow-2xl shadow-blue-500/60 hover:shadow-blue-400/80 hover:scale-[1.02] transition-all duration-300 group"
              >
                <Calculator className="mr-2 h-5 w-5 group-hover:rotate-12 transition-transform" />
                Generate Balance Sheet
              </Button>
            </CardContent>
          </Card>

          {/* Results Card */}
          {balanceSheet && (
            <Card
              className={`backdrop-blur-2xl ${balanceSheet.balanced ? 'bg-slate-800/90 border-emerald-400/60 shadow-emerald-500/60' : 'bg-slate-800/90 border-red-400/60 shadow-red-500/60'} border-2 shadow-2xl rounded-3xl overflow-hidden group hover:-translate-y-2 transition-all duration-500 animate-in fade-in slide-in-from-right`}
            >
              <div className={`absolute inset-0 bg-gradient-to-br ${balanceSheet.balanced ? 'from-emerald-500/10 via-transparent to-cyan-500/10' : 'from-red-500/10 via-transparent to-orange-500/10'} opacity-0 group-hover:opacity-100 transition-opacity duration-500`} />

              {/* Status Badge */}
              <div className="absolute top-6 right-6 z-10">
                <div className={`px-4 py-2 rounded-full backdrop-blur-xl ${balanceSheet.balanced ? 'bg-emerald-500/30 border border-emerald-400/50' : 'bg-red-500/30 border border-red-400/50'} flex items-center gap-2 shadow-lg`}>
                  {balanceSheet.balanced ? (
                    <>
                      <CheckCircle className="h-4 w-4 text-emerald-300" />
                      <span className="text-emerald-100 font-bold text-sm">Balanced</span>
                    </>
                  ) : (
                    <>
                      <AlertCircle className="h-4 w-4 text-red-300" />
                      <span className="text-red-100 font-bold text-sm">Unbalanced</span>
                    </>
                  )}
                </div>
              </div>

              <CardHeader className="relative pt-8">
                <CardTitle className="text-2xl font-bold text-white">Balance Sheet Report</CardTitle>
                <CardDescription className={balanceSheet.balanced ? "text-emerald-200" : "text-red-200"}>
                  {balanceSheet.balanced ? "Balance sheet is balanced ✓" : "Balance sheet is NOT balanced"}
                </CardDescription>
              </CardHeader>

              <CardContent className="space-y-6 relative">
                {/* Assets Display */}
                <div className="p-6 rounded-2xl bg-gradient-to-br from-blue-500/10 to-cyan-500/10 border border-blue-400/20 backdrop-blur-xl">
                  <h3 className="font-bold mb-4 text-white text-lg">Assets</h3>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center text-white py-2">
                      <span className="font-medium">Current Assets</span>
                      <span className="font-bold text-cyan-300">₹{balanceSheet.currentAssets.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between items-center text-white py-2">
                      <span className="font-medium">Non-Current Assets</span>
                      <span className="font-bold text-cyan-300">₹{balanceSheet.nonCurrentAssets.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between items-center font-bold border-t border-blue-400/30 pt-3 mt-3">
                      <span className="text-white text-lg">Total Assets</span>
                      <span className="text-xl text-white drop-shadow-[0_0_20px_rgba(6,182,212,0.8)]">₹{balanceSheet.totalAssets.toFixed(2)}</span>
                    </div>
                  </div>
                </div>

                {/* Liabilities Display */}
                <div className="p-6 rounded-2xl bg-gradient-to-br from-orange-500/10 to-red-500/10 border border-orange-400/20 backdrop-blur-xl">
                  <h3 className="font-bold mb-4 text-white text-lg">Liabilities</h3>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center text-white py-2">
                      <span className="font-medium">Current Liabilities</span>
                      <span className="font-bold text-orange-300">₹{balanceSheet.currentLiabilities.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between items-center text-white py-2">
                      <span className="font-medium">Non-Current Liabilities</span>
                      <span className="font-bold text-orange-300">₹{balanceSheet.nonCurrentLiabilities.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between items-center font-bold border-t border-orange-400/30 pt-3 mt-3">
                      <span className="text-white text-lg">Total Liabilities</span>
                      <span className="text-xl text-white drop-shadow-[0_0_20px_rgba(249,115,22,0.8)]">₹{balanceSheet.totalLiabilities.toFixed(2)}</span>
                    </div>
                  </div>
                </div>

                {/* Equity Display */}
                <div className="p-6 rounded-2xl bg-gradient-to-br from-green-500/10 to-emerald-500/10 border border-green-400/20 backdrop-blur-xl">
                  <h3 className="font-bold mb-4 text-white text-lg">Equity</h3>
                  <div className="space-y-3">
                    <div className="flex justify-between items-center text-white py-2">
                      <span className="font-medium">Equity</span>
                      <span className="font-bold text-emerald-300">₹{balanceSheet.equity.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between items-center font-bold border-t border-green-400/30 pt-3 mt-3">
                      <span className="text-white text-lg">Total Liabilities + Equity</span>
                      <span className="text-xl text-white drop-shadow-[0_0_20px_rgba(16,185,129,0.8)]">₹{balanceSheet.totalLiabilitiesEquity.toFixed(2)}</span>
                    </div>
                  </div>
                </div>

                <Button
                  onClick={downloadReport}
                  className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-bold py-6 rounded-xl shadow-2xl shadow-blue-500/60 hover:shadow-blue-400/80 hover:scale-[1.02] transition-all duration-300 group"
                >
                  <Download className="mr-2 h-5 w-5 group-hover:translate-y-1 transition-transform" />
                  Download Report
                </Button>
              </CardContent>
            </Card>
          )}
        </div>
      </main>
    </div>
  );
};

export default BalanceSheet;