import { useState } from "react";
import { VoiceButton } from "@/components/ui/VoiceButton";
import { Button } from "@/components/ui/button";
import { API_ENDPOINTS } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Calculator, Download, TrendingUp, TrendingDown, DollarSign, Sparkles, BarChart3 } from "lucide-react";
import { useNavigate } from "react-router-dom";

const ProfitLoss = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    sales: "",
    serviceIncome: "",
    interestIncome: "",
    otherIncome: "",
    salaries: "",
    rent: "",
    utilities: "",
    otherExpenses: "",
  });

  const [statement, setStatement] = useState(null);
  const [showResult, setShowResult] = useState(false);

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const generateStatement = async () => {
    // Parse all values with default 0
    const sales = parseFloat(formData.sales) || 0;
    const serviceIncome = parseFloat(formData.serviceIncome) || 0;
    const interestIncome = parseFloat(formData.interestIncome) || 0;
    const otherIncome = parseFloat(formData.otherIncome) || 0;
    const salaries = parseFloat(formData.salaries) || 0;
    const rent = parseFloat(formData.rent) || 0;
    const utilities = parseFloat(formData.utilities) || 0;
    const otherExpenses = parseFloat(formData.otherExpenses) || 0;

    // Calculate totals like Python file
    const totalRevenue = sales + serviceIncome + interestIncome + otherIncome;
    const totalExpenses = salaries + rent + utilities + otherExpenses;
    const netProfit = totalRevenue - totalExpenses;

    const result = {
      sales,
      serviceIncome,
      interestIncome,
      otherIncome,
      totalRevenue,
      salaries,
      rent,
      utilities,
      otherExpenses,
      totalExpenses,
      netProfit,
      profitable: netProfit > 0,
    };

    setStatement(result);
    setShowResult(true);

    try {
      const res = await fetch(`${API_ENDPOINTS.PROFIT_LOSS}/add`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(result),
      });
      const data = await res.json();
      if (!res.ok) console.error("Error saving data:", data);
    } catch (error) {
      console.error("Error connecting to backend:", error);
    }
  };

  const downloadPDF = () => {
    if (!statement) return;

    const content = `
╔═══════════════════════════════════════════════╗
║       PROFIT & LOSS STATEMENT - ${new Date().toLocaleDateString()}      ║
╚═══════════════════════════════════════════════╝

REVENUE & INCOME
────────────────────────────────────────────────
Sales:                     ₹${statement.sales.toFixed(2)}
Service Income:            ₹${statement.serviceIncome.toFixed(2)}
Interest Income:           ₹${statement.interestIncome.toFixed(2)}
Other Income:              ₹${statement.otherIncome.toFixed(2)}
────────────────────────────────────────────────
TOTAL REVENUE:             ₹${statement.totalRevenue.toFixed(2)}

EXPENSES
────────────────────────────────────────────────
Salaries:                  ₹${statement.salaries.toFixed(2)}
Rent:                      ₹${statement.rent.toFixed(2)}
Utilities:                 ₹${statement.utilities.toFixed(2)}
Other Expenses:            ₹${statement.otherExpenses.toFixed(2)}
────────────────────────────────────────────────
TOTAL EXPENSES:            ₹${statement.totalExpenses.toFixed(2)}

════════════════════════════════════════════════
NET ${statement.profitable ? 'PROFIT' : 'LOSS'}:                ₹${statement.netProfit.toFixed(2)}
════════════════════════════════════════════════

Status: ${statement.profitable ? '✓ PROFITABLE' : '✗ LOSS INCURRED'}

Generated by Financial Automation Platform
Powered by Advanced Financial Analytics Engine ✨
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `ProfitLoss_Statement_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const handleBackToDashboard = () => {
    navigate("/dashboard");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-950 text-white overflow-hidden relative">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-[linear-gradient(rgba(59,130,246,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(59,130,246,0.03)_1px,transparent_1px)] bg-[size:50px_50px]" />
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-indigo-600/10 rounded-full blur-[120px] pointer-events-none" />

      {/* Floating particles */}
      <div className="absolute top-20 left-20 w-2 h-2 bg-blue-400 rounded-full animate-ping" />
      <div className="absolute top-40 right-40 w-2 h-2 bg-cyan-400 rounded-full animate-ping" style={{ animationDelay: '1s' }} />
      <div className="absolute bottom-40 left-60 w-2 h-2 bg-indigo-400 rounded-full animate-ping" style={{ animationDelay: '2s' }} />

      {/* Header */}
      <header className="relative backdrop-blur-xl bg-white/5 border-b border-blue-400/20 shadow-2xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Button
            variant="ghost"
            onClick={handleBackToDashboard}
            className="mb-4 text-blue-200 hover:text-blue-100 hover:bg-white/10 backdrop-blur-md transition-all duration-300 hover:-translate-x-1"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
          <div className="flex items-center gap-4">
            <div className="p-3 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-2xl backdrop-blur-xl border border-blue-400/30">
              <BarChart3 className="h-8 w-8 text-blue-400" />
            </div>
            <div>
              <h1 className="text-4xl font-black bg-gradient-to-r from-blue-400 via-cyan-400 to-indigo-400 bg-clip-text text-transparent drop-shadow-[0_0_30px_rgba(59,130,246,0.8)]">
                Profit & Loss Statement
              </h1>
              <p className="text-blue-200/80 font-medium mt-1">Generate, analyze, and download P&L reports</p>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Input Card */}
          <Card className="backdrop-blur-2xl bg-white/10 border border-blue-400/20 shadow-2xl shadow-blue-500/20 rounded-3xl overflow-hidden transition-all duration-500 hover:shadow-blue-500/40 hover:-translate-y-2">
            <CardHeader className="relative">
              <CardTitle className="text-2xl font-black text-blue-100 flex items-center gap-3">
                <DollarSign className="h-6 w-6 text-cyan-400" />
                Enter P&L Data
              </CardTitle>
              <CardDescription className="text-blue-200/70">
                Input your company's financial details
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Revenue Section */}
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-blue-100 border-b border-blue-400/30 pb-2">💰 Revenue</h3>
                {[
                  { field: "sales", label: "Sales", icon: "📊" },
                  { field: "serviceIncome", label: "Service Income", icon: "🔧" },
                  { field: "interestIncome", label: "Interest Income", icon: "📈" },
                  { field: "otherIncome", label: "Other Income", icon: "💰" },
                ].map(({ field, label, icon }) => (
                  <div key={field} className="space-y-2">
                    <Label htmlFor={field} className="text-blue-100 font-bold flex items-center gap-2">
                      <span>{icon}</span> {label} (₹)
                    </Label>
                    <div className="flex items-center gap-2">
                      <Input
                        id={field}
                        type="number"
                        placeholder="0.00"
                        value={formData[field]}
                        onChange={(e) => handleInputChange(field, e.target.value)}
                        className="bg-white/5 backdrop-blur-xl text-blue-100 border border-blue-400/30 rounded-xl h-12"
                      />
                      <VoiceButton
                        onTranscript={(text) => handleInputChange(field, text)}
                        onClear={() => handleInputChange(field, "")}
                      />
                    </div>
                  </div>
                ))}
              </div>

              {/* Expenses Section */}
              <div className="space-y-4">
                <h3 className="text-lg font-bold text-blue-100 border-b border-blue-400/30 pb-2">💸 Expenses</h3>
                {[
                  { field: "salaries", label: "Salaries", icon: "👥" },
                  { field: "rent", label: "Rent", icon: "🏢" },
                  { field: "utilities", label: "Utilities", icon: "⚡" },
                  { field: "otherExpenses", label: "Other Expenses", icon: "📋" },
                ].map(({ field, label, icon }) => (
                  <div key={field} className="space-y-2">
                    <Label htmlFor={field} className="text-blue-100 font-bold flex items-center gap-2">
                      <span>{icon}</span> {label} (₹)
                    </Label>
                    <div className="flex items-center gap-2">
                      <Input
                        id={field}
                        type="number"
                        placeholder="0.00"
                        value={formData[field]}
                        onChange={(e) => handleInputChange(field, e.target.value)}
                        className="bg-white/5 backdrop-blur-xl text-blue-100 border border-blue-400/30 rounded-xl h-12"
                      />
                      <VoiceButton
                        onTranscript={(text) => handleInputChange(field, text)}
                        onClear={() => handleInputChange(field, "")}
                      />
                    </div>
                  </div>
                ))}
              </div>

              <Button
                onClick={generateStatement}
                className="w-full h-14 bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-500 hover:to-blue-600 text-white font-bold text-lg rounded-xl shadow-2xl transition-all duration-300 hover:scale-[1.02]"
              >
                <Calculator className="mr-2 h-5 w-5" />
                Generate P&L Statement
              </Button>
            </CardContent>
          </Card>

          {/* Result Card */}
          {showResult && statement && (
            <Card className={`backdrop-blur-2xl border-2 shadow-2xl rounded-3xl overflow-hidden transition-all duration-700 animate-in fade-in ${statement.profitable ? 'border-emerald-400/60 shadow-emerald-500/60' : 'border-red-400/60 shadow-red-500/60'}`}>
              <CardHeader className="relative">
                <CardTitle className="text-2xl font-black flex items-center gap-3 text-white">
                  {statement.profitable ? <TrendingUp className="h-6 w-6 text-emerald-400" /> : <TrendingDown className="h-6 w-6 text-red-400" />}
                  Financial Summary
                </CardTitle>
                <CardDescription className={statement.profitable ? 'text-emerald-200/80' : 'text-red-200/80'}>
                  Detailed profit & loss breakdown
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-3">
                  <h4 className="text-lg font-bold text-white mb-2">💰 Revenue</h4>
                  {[
                    { label: "Sales", value: statement.sales },
                    { label: "Service Income", value: statement.serviceIncome },
                    { label: "Interest Income", value: statement.interestIncome },
                    { label: "Other Income", value: statement.otherIncome },
                  ].map(({ label, value }, i) => (
                    <div key={i} className="flex justify-between items-center p-3 rounded-xl bg-white/5 border border-white/10">
                      <span className="text-white/90">{label}</span>
                      <span className="font-bold text-white">₹{value.toFixed(2)}</span>
                    </div>
                  ))}
                  <div className="flex justify-between items-center p-3 rounded-xl bg-blue-500/20 border border-blue-400/30">
                    <span className="font-bold text-white">Total Revenue</span>
                    <span className="font-bold text-white">₹{statement.totalRevenue.toFixed(2)}</span>
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="text-lg font-bold text-white mb-2">💸 Expenses</h4>
                  {[
                    { label: "Salaries", value: statement.salaries },
                    { label: "Rent", value: statement.rent },
                    { label: "Utilities", value: statement.utilities },
                    { label: "Other Expenses", value: statement.otherExpenses },
                  ].map(({ label, value }, i) => (
                    <div key={i} className="flex justify-between items-center p-3 rounded-xl bg-white/5 border border-white/10">
                      <span className="text-white/90">{label}</span>
                      <span className="font-bold text-white">₹{value.toFixed(2)}</span>
                    </div>
                  ))}
                  <div className="flex justify-between items-center p-3 rounded-xl bg-red-500/20 border border-red-400/30">
                    <span className="font-bold text-white">Total Expenses</span>
                    <span className="font-bold text-white">₹{statement.totalExpenses.toFixed(2)}</span>
                  </div>
                </div>

                <div className={`flex justify-between items-center p-5 rounded-2xl border-2 mt-6 ${statement.profitable ? 'bg-emerald-600/20 border-emerald-400/60' : 'bg-red-600/20 border-red-400/60'}`}>
                  <span className="text-xl font-black text-white">Net {statement.profitable ? 'Profit' : 'Loss'}</span>
                  <span className="text-3xl font-black text-white">₹{statement.netProfit.toFixed(2)}</span>
                </div>

                <Button
                  className={`w-full h-14 text-white font-bold text-lg rounded-2xl shadow-2xl transition-all duration-300 mt-6 ${statement.profitable ? 'bg-emerald-600 hover:bg-emerald-500' : 'bg-red-600 hover:bg-red-500'}`}
                  onClick={downloadPDF}
                >
                  <Download className="mr-2 h-5 w-5" />
                  Download P&L Statement
                </Button>
              </CardContent>
            </Card>
          )}

          {!showResult && (
            <Card className="backdrop-blur-2xl bg-white/5 border border-blue-400/10 shadow-xl rounded-3xl overflow-hidden flex items-center justify-center min-h-[600px]">
              <div className="text-center p-8">
                <BarChart3 className="h-12 w-12 text-blue-400 mx-auto mb-6 animate-pulse" />
                <h3 className="text-2xl font-bold text-blue-200 mb-3">Ready to Analyze</h3>
                <p className="text-blue-300/60">Enter your financial data to generate a statement</p>
              </div>
            </Card>
          )}
        </div>
      </main>
    </div>
  );
};

export default ProfitLoss;